version: '3.7'

services:
    otrs:
        build: 
            context: ./otrs
            dockerfile: Dockerfile
        ports: 
            - 8080:80
        volumes: 
            - ./src:/data/src
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        restart: always
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: root
