version: '3.7'

services:
    otrs:
        build: 
            context: ./otrs
            dockerfile: Dockerfile
        ports: 
            - 8080:80
        volumes: 
            - ./src:/data/src
        depends_on:
            - mariadb

    mariadb:
        build: 
            context: ./mariadb
            dockerfile: Dockerfile
        restart: always
        ports: 
            - 3360:3360
        environment: 
            MYSQL_ROOT_PASSWORD: root
